//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSCWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaints
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Complaints()
        {
            this.ComplaintImages = new HashSet<ComplaintImages>();
            this.ComplaintsLows = new HashSet<ComplaintsLows>();
        }
    
        public long Id { get; set; }
        public string ShopName { get; set; }
        public string ShopAddress { get; set; }
        public Nullable<System.DateTime> DateOfInspection { get; set; }
        public string Comments { get; set; }
        public string Violations { get; set; }
        public string GpsLocations { get; set; }
        public string UserId { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> SpeciesId { get; set; }
        public Nullable<int> ComplainStatus { get; set; }
        public string GroupName { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsRejecet { get; set; }
        public string CommentForRejection { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<bool> IsRegister { get; set; }
        public Nullable<bool> IsEmailSend { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Citys Citys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintImages> ComplaintImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintsLows> ComplaintsLows { get; set; }
        public virtual Species Species { get; set; }
    }
}
