//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSCWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintList
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ShopName { get; set; }
        public string ShopAddress { get; set; }
        public Nullable<System.DateTime> DateOfInspection { get; set; }
        public string Comments { get; set; }
        public string CityName { get; set; }
        public string SpeciesName { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsRejecet { get; set; }
        public Nullable<bool> IsRegister { get; set; }
        public Nullable<bool> IsEmailSend { get; set; }
    }
}
