//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSCWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetailWithRole
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phonenumber { get; set; }
        public string City { get; set; }
        public string UserRole { get; set; }
        public string RoleId { get; set; }
    }
}
